/*****************************************************************************
 * File generated by HDevelop for Halcon/Cpp Version 17.12
 *
 * Do not modify!
 *****************************************************************************/

#ifndef SCALEDSHAPEMATCH_H
#define SCALEDSHAPEMATCH_H

#ifndef __APPLE__
  #include <halconcpp/HalconCpp.h>
#else
  #include <HALCONCpp/HalconCpp.h>
#endif

namespace ScaledShapeMatch {

/*****************************************************************************
 * SetResourcePath
 *****************************************************************************
 * Use SetResourcePath in your application to specify the location of the 
 * HDevelop script or procedure library.
 *****************************************************************************/
  void SetResourcePath(const char* resource_path);

  void createTemplateImg(
    HalconCpp::HObject const& Image,
    HalconCpp::HTuple* ModelID);


  void scaled_shape_match(
    HalconCpp::HObject const& Image,
    HalconCpp::HTuple const& ModelID,
    HalconCpp::HTuple* Row,
    HalconCpp::HTuple* Column,
    HalconCpp::HTuple* Angle,
    HalconCpp::HTuple* Scale,
    HalconCpp::HTuple* Score);


    
};

#endif